name: test-init-env
on: workflow_dispatch

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: "1/8: purge firefox"
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo -E apt -yqq purge firefox

      - name: "2/8: apt update"
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo -E apt -yqq update

      - name: "3/8: apt full-upgrade"
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo -E apt -yqq full-upgrade

      - name: "4/8: autoremove"
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo -E apt -yqq autoremove --purge

      - name: "5/8: autoclean"
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo -E apt -yqq autoclean

      - name: "6/8: clean"
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo -E apt -yqq clean

      - name: "7/8: install dos2unix libfuse-dev"
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo -E apt -yqq install dos2unix libfuse-dev

      - name: "8/8: immortalwrt init script"
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo bash -c 'bash <(curl -sL https://build-scripts.immortalwrt.org/init_build_environment.sh)'
          sudo -E systemctl daemon-reload
          sudo -E timedatectl set-timezone "Asia/Shanghai"

      - name: "DONE"
        run: echo "All steps completed!"
